# Generated by Django 5.1.7 on 2025-06-13 10:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture of the user', null=True, upload_to=accounts.models.user_profile_path),
        ),
    ]
