# Generated by Django 5.1.7 on 2025-06-15 03:34

import accounts.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture (max 512x512px, 1MB, formats: JPEG, PNG)', null=True, upload_to=accounts.models.user_profile_path, validators=[core.validators.FileSizeValidator(1), core.validators.ImageDimensionsValidator(512, 512), core.validators.ImageFormatValidator(['JPEG', 'PNG'])]),
        ),
    ]
