# Generated by Django 5.1.7 on 2025-06-16 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_profile_picture'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='The organisation this user owns or manages, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organizations.organisation'),
        ),
    ]
