# Generated by Django 5.1.7 on 2025-06-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='admin_remarks',
            field=models.TextField(blank=True, help_text='Internal remarks from an admin regarding the verification.', null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='application_notes',
            field=models.TextField(blank=True, help_text='Notes submitted by the organisation during application.', null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='The current verification status of the organisation.', max_length=10),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='verified',
            field=models.BooleanField(default=False, help_text='True if the organisation has been verified by an admin.'),
        ),
    ]
