# Generated by Django 5.1.7 on 2025-06-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0003_campaign_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='admin_remarks',
            field=models.TextField(blank=True, help_text="Internal remarks from an admin regarding the campaign's status.", null=True),
        ),
    ]
