# Generated by Django 5.1.7 on 2025-06-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0005_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='admin_remarks',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='application_notes',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='verified',
        ),
        migrations.AddField(
            model_name='organisation',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
