# Generated by Django 5.1.7 on 2025-06-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0006_remove_organisation_admin_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='A cover image for your campaign page.', null=True, upload_to='campaign_covers/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, help_text='Tell the story of your campaign.', null=True),
        ),
    ]
