# Generated by Django 5.1.7 on 2025-06-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0007_campaign_cover_image_campaign_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
