# Generated by Django 5.1.7 on 2025-06-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0008_organisation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='comment',
            field=models.TextField(blank=True, help_text='Comments from the donor', null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Unique reference number for the donation', max_length=50, null=True, unique=True),
        ),
    ]
