# Generated by Django 5.1.7 on 2025-06-13 12:35

import funding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0009_donation_comment_donation_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=funding.models.org_banner_path),
        ),
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=funding.models.org_logo_path),
        ),
    ]
