# Generated by Django 5.1.7 on 2025-06-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0010_organisation_banner_organisation_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', max_length=10),
        ),
    ]
