# Generated by Django 5.1.7 on 2025-06-15 03:34

import core.validators
import funding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0011_alter_campaign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='A cover image for your campaign page (max 1920x1080px, 5MB, formats: JPEG, PNG).', null=True, upload_to='campaign_covers/', validators=[core.validators.FileSizeValidator(5), core.validators.ImageDimensionsValidator(1920, 1080), core.validators.ImageFormatValidator(['JPEG', 'PNG'])]),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='banner',
            field=models.ImageField(blank=True, help_text='Organization banner (max 1920x480px, 3MB, formats: JPEG, PNG)', null=True, upload_to=funding.models.org_banner_path, validators=[core.validators.FileSizeValidator(3), core.validators.ImageDimensionsValidator(1920, 480), core.validators.ImageFormatValidator(['JPEG', 'PNG'])]),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, help_text='Organization logo (max 800x800px, 2MB, formats: JPEG, PNG, SVG)', null=True, upload_to=funding.models.org_logo_path, validators=[core.validators.FileSizeValidator(2), core.validators.ImageDimensionsValidator(800, 800), core.validators.ImageFormatValidator(['JPEG', 'PNG', 'SVG'])]),
        ),
    ]
